language: node_js
node_js:
  - 12

cache:
  directories:
    - "node_modules"

sudo: required
addons:
  chrome: stable

instal:
  - npm ci

before_script:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
