language: node_js
node_js:
  - 12

cache:
  directories:
    - "node_modules"

sudo: required
dist: bionic
services:
  - xvfb
addons:
  chrome: stable

before_script:
  - export DISPLAY=:99.0
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

instal:
  - npm ci

