language: node_js
node_js:
  - 12

cache:
  directories:
    - "node_modules"

sudo: required
services:
  - xvfb
addons:
  chrome: stable

before_script:
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser

instal:
  - npm ci

